---
- name: cups_lpadmin | Deploy printers
  cups_lpadmin:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    printer_or_class: "{{ item.printer_or_class | default('printer') }}"
    uri: "{{ item.uri }}"
    driver: "{{ item.driver | default('model') }}"
    model: "{% if item.driver is defined and item.driver == 'ppd' %}
              {{- vars['cups_lpadmin_temp_path'] + '/' + item.model -}}
            {% else %}
              {{- item.model | default('raw') -}}
            {% endif %}"
    enabled: "{{ item.enabled | default('true') }}"
    shared: "{{ item.shared | default('false') }}"
    default: "{{ item.default | default('false') }}"
    location: "{{ item.location | default('') }}"
    info: "{{ item.info | default('') }}"
    options: "{{ item.options | default('{ }') }}"
  loop: "{{ vars['cups_lpadmin_cups_settings'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ item.name }}"
